// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmbpfAllowedUidKey struct {
	_        structs.HostLayout
	PolicyId uint32
	Uid      uint32
}

type lsmbpfControllerSettings struct {
	_                  structs.HostLayout
	DiagnosticsEnabled uint32
}

type lsmbpfObjectKey struct {
	_      structs.HostLayout
	Device uint64
	Inode  uint64
}

type lsmbpfPolicyValue struct {
	_           structs.HostLayout
	PolicyId    uint32
	Mode        uint32
	ExpiresAtNs uint64
}

// loadLsmbpf returns the embedded CollectionSpec for lsmbpf.
func loadLsmbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmbpf: %w", err)
	}

	return spec, err
}

// loadLsmbpfObjects loads lsmbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmbpfObjects
//	*lsmbpfPrograms
//	*lsmbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmbpfSpecs struct {
	lsmbpfProgramSpecs
	lsmbpfMapSpecs
	lsmbpfVariableSpecs
}

// lsmbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmbpfProgramSpecs struct {
	HandleFilePermission *ebpf.ProgramSpec `ebpf:"handle_file_permission"`
	HandleInodeRename    *ebpf.ProgramSpec `ebpf:"handle_inode_rename"`
	HandleInodeSetattr   *ebpf.ProgramSpec `ebpf:"handle_inode_setattr"`
	HandleInodeUnlink    *ebpf.ProgramSpec `ebpf:"handle_inode_unlink"`
}

// lsmbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmbpfMapSpecs struct {
	AllowedUids      *ebpf.MapSpec `ebpf:"allowed_uids"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	ProtectedObjects *ebpf.MapSpec `ebpf:"protected_objects"`
	Settings         *ebpf.MapSpec `ebpf:"settings"`
	Stats            *ebpf.MapSpec `ebpf:"stats"`
}

// lsmbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmbpfVariableSpecs struct {
}

// lsmbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmbpfObjects struct {
	lsmbpfPrograms
	lsmbpfMaps
	lsmbpfVariables
}

func (o *lsmbpfObjects) Close() error {
	return _LsmbpfClose(
		&o.lsmbpfPrograms,
		&o.lsmbpfMaps,
	)
}

// lsmbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmbpfMaps struct {
	AllowedUids      *ebpf.Map `ebpf:"allowed_uids"`
	Events           *ebpf.Map `ebpf:"events"`
	ProtectedObjects *ebpf.Map `ebpf:"protected_objects"`
	Settings         *ebpf.Map `ebpf:"settings"`
	Stats            *ebpf.Map `ebpf:"stats"`
}

func (m *lsmbpfMaps) Close() error {
	return _LsmbpfClose(
		m.AllowedUids,
		m.Events,
		m.ProtectedObjects,
		m.Settings,
		m.Stats,
	)
}

// lsmbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmbpfVariables struct {
}

// lsmbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmbpfPrograms struct {
	HandleFilePermission *ebpf.Program `ebpf:"handle_file_permission"`
	HandleInodeRename    *ebpf.Program `ebpf:"handle_inode_rename"`
	HandleInodeSetattr   *ebpf.Program `ebpf:"handle_inode_setattr"`
	HandleInodeUnlink    *ebpf.Program `ebpf:"handle_inode_unlink"`
}

func (p *lsmbpfPrograms) Close() error {
	return _LsmbpfClose(
		p.HandleFilePermission,
		p.HandleInodeRename,
		p.HandleInodeSetattr,
		p.HandleInodeUnlink,
	)
}

func _LsmbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmbpf_x86_bpfel.o
var _LsmbpfBytes []byte
